services:
  back-end:
    build:
      context: ./backend/todo
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:postgresql://postgrespring/task
      DB_USERNAME: postgres
      DB_PASSWORD: dramblysAdminas123.
  front-end:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
  postgrespring:
    image: postgres:15.3-alpine3.18
    volumes:
      - dbdata:/var/lib/postgresql/data  
    environment:
      - POSTGRES_PASSWORD=dramblysAdminas123.
      - POSTGER_USER=postgres
      - POSTGRES_DB=task

volumes:
  dbdata: